name: C++ Native Application CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**/*.cpp'
      - 'src/**/*.h'
      - 'include/**/*.h'
      - 'CMakeLists.txt'
      - '.github/workflows/cpp-native.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**/*.cpp'
      - 'src/**/*.h'
      - 'include/**/*.h'
      - 'CMakeLists.txt'
      - '.github/workflows/cpp-native.yml'

jobs:
  cpp-build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        build_type: [Debug, Release]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup CMake
      uses: lukka/get-cmake@latest
      
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        
    - name: Build C++ application
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }} --parallel
        
    - name: Verify executable exists
      run: |
        cd build
        if (Test-Path "bin/${{ matrix.build_type }}/SecuritySentinel.exe") {
          Write-Output "✅ SecuritySentinel.exe built successfully"
          Get-ChildItem "bin/${{ matrix.build_type }}/SecuritySentinel.exe" | Format-List
        } else {
          Write-Error "❌ SecuritySentinel.exe not found"
          Get-ChildItem -Recurse | Where-Object {$_.Name -like "*SecuritySentinel*"}
          exit 1
        }
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.build_type == 'Release'
      with:
        name: cpp-build-release
        path: build/bin/Release/
        retention-days: 30