name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

jobs:
  quick-checks:
    name: Quick PR Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Fast build check
      run: |
        echo "🔍 Running fast validation checks..."
        
        # TypeScript compilation
        echo "📝 Checking TypeScript compilation..."
        npm run lint
        
        # Build verification
        echo "🏗️ Verifying build process..."
        npm run build
        
        echo "✅ All quick checks passed!"
        
    - name: PR Status Comment
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ PR ready for review - all quick checks passed!"
        else
          echo "❌ PR has issues - please check the build logs"
        fi